'''Este archivo contiene los mensajes que le vamos a mostrar al usuario
con las funciones gamelib.input y gamelib.say '''

MENSAJE_INFO_POKEDEX = '''La Pokédex, en el mundo ficticio de Pokémon, es una enciclopedia electrónica portátil que los entrenadores Pokémon llevan consigo para registrar automáticamente las fichas de todas las diversas especies Pokémon vistas y capturadas durante su viaje como entrenadores.​​'''
MENSAJE_INFO_POKEMONS = ''''Pokémon = Una contracción del japonés Poketto Monsutā, que significa monstruo de bolsillo.'''
MENSAJE_INFO_EQUIPOS = 'Cada equipo de Pokémon esta formado por 4 pokemones, de los cuales cada uno tiene un moveset formado por 6 movimientos'
MENSAJE_NUEVO_NOMBRE_EQUIPO = '¿Como queres llamar al nuevo equipo?'
MENSAJES_VERIFICACION_BORRAR_EQUIPO_ACTUAL = '¿Estas seguro que queres borrar los pokemones?\nSe perderan todos los pokemones con sus movimientos\ns para confirmar\notro para regresar'
MENSAJE_DATO_NO_EXISTE = 'El dato ingresado no existe'
MENSAJE_INGRESE_POKEMON = 'Ingrese un pokemon para agregar al equipo'
MENSAJE_POKEMON_INEXISTENTE = 'No existe ese pokemon'
MENSAJE_POKEMON_SIN_MOVS = 'No es posible agregar este pokemon a tu equipo porque no tiene movimientos'
MENSAJE_INGRESE_NUMERO_MOV = 'Ingrese un movimiento obligatoriamente para agregar el pokemon\nIngrese el numero correspondiente'
MENSAJE_NUMERO_INCORRECTO = 'No ingresaste un numero'
MENSAJE_NUMERO_NO_ESTABA_EN_LAS_OPCIONES = 'El numero no estaba en las opciones'
MENSAJE_INGRESE_MOVIMIENTO = 'Ingrese el numero del movimiento elegido'
MENSAJE_INGRESE_NUMERO_MOVIMIENTO_A_BORRAR = 'Ingrese el numero del movimiento a borrar\n'
MENSAJE_INGRESE_POKEMON = 'Ingresa un numero o nombre de un Pokémon'
MENSAJE_VERIFICACION_GUARDAR_DATOS = '¿Queres guardar los datos?\ns para confirmar\notro para no'
MENSAJE_DATOS_GUARDADOS = '¡Datos guardados correctamente!'
MENSAJE_VERIFICACION_BORRAR_POKEMON_ACTUAL = '¿Estas seguro que quieres borrar el pokemon actual?\n¡Se perderan los movimientos elegidos!\ns para confirmar\notro para cancelar'
MENSAJE_NO_SE_PUEDEN_AGREGAR_POKEMONS = 'No se pueden agregar más pokemons en este equipo.'
MENSAJE_POKEMON_YA_ESTA_EN_EL_EQUIPO = 'Este pokemon ya se encuentra en el equipo.'
MENSAJE_CANTIDAD_MOV_EXCEDIDA = 'La cantidad de movimientos excede el limite (máx. 4).'
MENSAJE_MOV_YA_INCLUIDO = 'EL movimiento ya esta incluido en el Move-Set'
MENSAJE_NO_SE_PUEDE_BORRAR_MOV = 'No se puede borrar (minimo un movimiento por pokemon)'
MENSAJE_VERIFICACION_GUARDAR_ANTES_DE_SALIR = '¿Queres guardar los datos antes de salir?\ns para confirmar\notro para no'